# Generated by Django 6.1 on 2026-08-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exame', models.CharField(choices=[('glicemia', 'Glicemia'), ('hemograma', 'Hemograma')], max_length=50)),
                ('data', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odisseu.paciente')),
            ],
        ),
    ]
