# Generated by Django 6.1 on 2026-08-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0002_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('liberado', models.BooleanField(default=False)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='odisseu.agendamento')),
            ],
        ),
    ]
