# Generated by Django 6.1 on 2026-08-15 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0003_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado',
            name='valor',
        ),
        migrations.CreateModel(
            name='ResultadoParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=200)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='odisseu.resultado')),
            ],
        ),
    ]
