# Generated by Django 6.1 on 2026-08-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0004_remove_resultado_valor_resultadoparametro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='exame',
            field=models.CharField(choices=[('glicemia', 'Glicemia'), ('hemograma', 'Hemograma'), ('proteina_c', 'Proteína C reativa')], max_length=50),
        ),
    ]
