# Generated by Django 6.1 on 2026-08-16 14:14

import odisseu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0005_alter_agendamento_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='exame',
            field=models.CharField(choices=[('glicemia', 'Glicemia'), ('hemograma', 'Hemograma'), ('proteina', 'Proteína C reativa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(max_length=14, validators=[odisseu.validators.validate_cns]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, validators=[odisseu.validators.validate_cpf]),
        ),
    ]
