# Generated by Django 6.1 on 2026-08-16 14:36

import odisseu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0006_alter_agendamento_exame_alter_paciente_cns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(validators=[odisseu.validators.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=200, validators=[odisseu.validators.validate_nome]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=20, validators=[odisseu.validators.validate_telefone]),
        ),
    ]
