# Generated by Django 6.1 on 2026-08-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0007_alter_agendamento_data_alter_paciente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data',
            field=models.DateField(),
        ),
    ]
