# Generated by Django 6.1 on 2026-08-16 19:07

import odisseu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0008_alter_agendamento_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='solicitante',
            field=models.CharField(blank=True, max_length=200, validators=[odisseu.validators.validate_nome]),
        ),
    ]
