# Generated by Django 6.1 on 2026-08-22 16:05

import odisseu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0009_agendamento_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(max_length=18, validators=[odisseu.validators.validate_cns]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, validators=[odisseu.validators.validate_cpf]),
        ),
    ]
