# Generated by Django 6.1 on 2026-08-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0010_alter_paciente_cns_alter_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoparametro',
            name='percentual',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
