# Generated by Django 6.1 on 2026-08-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0011_resultadoparametro_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='exame',
            field=models.CharField(choices=[('glicemia', 'Glicemia'), ('hemograma', 'Hemograma'), ('proteina', 'Proteína C reativa'), ('sumario_urina', 'Sumário de Urina')], max_length=50),
        ),
    ]
