# Generated by Django 6.1 on 2026-08-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0012_alter_agendamento_exame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='exame',
            field=models.CharField(choices=[('glicemia', 'Glicemia'), ('hemograma', 'Hemograma'), ('proteina', 'Proteína C reativa'), ('sumario_urina', 'Sumário de Urina'), ('colesterol_total', 'Colesterol Total'), ('also', 'Antiestreptolisina O'), ('ureia', 'Uréia'), ('tgo', 'TGO'), ('tgp', 'TGP'), ('gp_sanguineo', 'Grupo Sanguíneo e fator RH')], max_length=50),
        ),
    ]
