# Generated by Django 6.1 on 2026-09-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0013_alter_agendamento_exame'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='senha',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
