# Generated by Django 6.1 on 2026-09-13 22:52

import odisseu.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0014_paciente_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cns',
            field=models.CharField(max_length=18, unique=True, validators=[odisseu.validators.validate_cns]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[odisseu.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='senha',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
