# Generated by Django 6.1 on 2026-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odisseu', '0015_alter_paciente_cns_alter_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
